### PR TITLE
Add a manifest file that names Coordinator as the main class for jar

### PR DESCRIPTION
**Pull request by ghost**
Just a simple manifest file that specifies Coordinator class as the main class when jar'ing the project.

### CODE REVIEW

**Comment by vsowrirajan** [comment]
This is already done as part of maven pom.xml under Maven shade plugin

**Comment by ghost** [comment]
Didn't realize that.  Have you used Maven to build a jar?  If so can you share the commands?

**Comment by vsowrirajan** [comment]
Sure.

*mvn clean install  - *It builds the jar under Distiller-server/target

Regards

Venkat
MapR Technologies, Inc.

**Comment by ghost** [comment]
Maven build worked fine for me.  Closing this.

**Comment by vsowrirajan** [comment]
In that case, shall I remove jars which are part of Distiller? As maven can handle all those things automatically.

**Comment by ghost** [comment]
sure.

**Pull request closed without merging**
